name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiY2VjZmFmNTktZGVjNi00ZDNmLTlkMmEtZmEwMjMzZjI2NTFjIiwidGVuYW50X2lkIjoiMDBmMTk4YjU1MzRiZDJmMjNiYzU5YzVmN2ViMjk0ZjgzM2ExY2U0ZWQ0MWRlNGJlMDFjOGU4YTNlZjNkOWFlNCIsImludGVybmFsX3NlY3JldCI6IjQyOGRmNzlkLTFmNzUtNDZiNC1hMWViLWE3YjdlNzdkZWEyMyJ9.a4Cka3uS0YQNbBk4bkX0tXFRMX75mGSvQHN18qk0AF4"
JWT_SECRET="rishie@813111"
